comment:
  layout: 'reach, diff, flags, files'
  behavior: default

ignore:
  - '.yarn'
  - '**/*.lock'
  - '.husky'
  - '.github'
  - '.vscode'
  - 'grafana'
  - '**/*.test.ts'
  - '**/*.test.ts.snap'
  - '**/*fixtures.ts'
  - '**/tests/'
  - '**/test/'
  - '**/generated/'
  - '**/dist/'
  - '**/vendor/'
  - '**/schemas/'
  - 'tsconfig.tsbuildinfo'
  - '**/*.cjs'
  - '**/*.md'
  - "**/*.json"

flag_management:
  default_rules:
    statuses:
      # Project-wide coverage must increase on every PR, with a 1% leeway
      - name_prefix: project-
        type: project
        target: auto
        threshold: 1%
      # Every PR must have a minimum of 90% coverage on adjusted lines
      - name_prefix: patch-
        type: patch
        target: 90%
